import { eq } from 'drizzle-orm'
import type { NodePgDatabase } from 'drizzle-orm/node-postgres'

import type * as schema from '../schema'
import { themes } from '../schema/themes.schema'
import type { ThemeConfig } from '../schema/themes.schema'

const PRESET_THEMES: { name: string; slug: string; config: ThemeConfig }[] = [
    // ── 1. Midnight Ocean ────────────────────────────────────────────────────
    {
        name: 'Midnight Ocean',
        slug: 'midnight-ocean',
        config: {
            light: {
                background: '#f8faff',
                foreground: '#0f172a',
                card: '#ffffff',
                cardForeground: '#0f172a',
                popover: '#ffffff',
                popoverForeground: '#0f172a',
                primary: '#1e40af',
                primaryForeground: '#ffffff',
                secondary: '#eff6ff',
                secondaryForeground: '#1e40af',
                muted: '#f1f5f9',
                mutedForeground: '#64748b',
                accent: '#0ea5e9',
                accentForeground: '#ffffff',
                destructive: '#dc2626',
                border: '#bfdbfe',
                input: '#bfdbfe',
                ring: '#3b82f6',
                chart1: '#1e40af',
                chart2: '#0ea5e9',
                chart3: '#38bdf8',
                chart4: '#0284c7',
                chart5: '#075985',
                sidebar: '#eff6ff',
                sidebarForeground: '#1e3a5f',
                sidebarPrimary: '#1e40af',
                sidebarPrimaryForeground: '#ffffff',
                sidebarAccent: '#dbeafe',
                sidebarAccentForeground: '#1e40af',
                sidebarBorder: '#bfdbfe',
                sidebarRing: '#3b82f6',
            },
            dark: {
                background: '#020817',
                foreground: '#e2e8f0',
                card: '#0f172a',
                cardForeground: '#e2e8f0',
                popover: '#0f172a',
                popoverForeground: '#e2e8f0',
                primary: '#60a5fa',
                primaryForeground: '#020817',
                secondary: '#1e293b',
                secondaryForeground: '#e2e8f0',
                muted: '#1e293b',
                mutedForeground: '#94a3b8',
                accent: '#0ea5e9',
                accentForeground: '#020817',
                destructive: '#7f1d1d',
                border: '#1e3a5f',
                input: '#1e3a5f',
                ring: '#60a5fa',
                chart1: '#60a5fa',
                chart2: '#38bdf8',
                chart3: '#7dd3fc',
                chart4: '#0ea5e9',
                chart5: '#bae6fd',
                sidebar: '#090f1f',
                sidebarForeground: '#94a3b8',
                sidebarPrimary: '#60a5fa',
                sidebarPrimaryForeground: '#020817',
                sidebarAccent: '#1e293b',
                sidebarAccentForeground: '#e2e8f0',
                sidebarBorder: '#1e3a5f',
                sidebarRing: '#60a5fa',
            },
            radius: '0.5',
            fontFamily: 'Inter',
            heroVariant: 'centered',
            heroBackground: 'gradient',
        },
    },

    // ── 2. Rose Quartz ───────────────────────────────────────────────────────
    {
        name: 'Rose Quartz',
        slug: 'rose-quartz',
        config: {
            light: {
                background: '#fff5f8',
                foreground: '#1c0511',
                card: '#ffffff',
                cardForeground: '#1c0511',
                popover: '#ffffff',
                popoverForeground: '#1c0511',
                primary: '#be185d',
                primaryForeground: '#ffffff',
                secondary: '#fdf2f8',
                secondaryForeground: '#be185d',
                muted: '#fce7f3',
                mutedForeground: '#9d174d',
                accent: '#f43f5e',
                accentForeground: '#ffffff',
                destructive: '#dc2626',
                border: '#fbcfe8',
                input: '#fbcfe8',
                ring: '#ec4899',
                chart1: '#be185d',
                chart2: '#f43f5e',
                chart3: '#fb7185',
                chart4: '#e879a0',
                chart5: '#c026d3',
                sidebar: '#fdf2f8',
                sidebarForeground: '#701a45',
                sidebarPrimary: '#be185d',
                sidebarPrimaryForeground: '#ffffff',
                sidebarAccent: '#fce7f3',
                sidebarAccentForeground: '#be185d',
                sidebarBorder: '#fbcfe8',
                sidebarRing: '#ec4899',
            },
            dark: {
                background: '#0d0208',
                foreground: '#fce7f3',
                card: '#1c0511',
                cardForeground: '#fce7f3',
                popover: '#1c0511',
                popoverForeground: '#fce7f3',
                primary: '#f472b6',
                primaryForeground: '#0d0208',
                secondary: '#2d0a1e',
                secondaryForeground: '#fce7f3',
                muted: '#2d0a1e',
                mutedForeground: '#d097b4',
                accent: '#f43f5e',
                accentForeground: '#0d0208',
                destructive: '#7f1d1d',
                border: '#4a0e2c',
                input: '#4a0e2c',
                ring: '#f472b6',
                chart1: '#f472b6',
                chart2: '#fb7185',
                chart3: '#fda4af',
                chart4: '#f43f5e',
                chart5: '#fecdd3',
                sidebar: '#0a0108',
                sidebarForeground: '#d097b4',
                sidebarPrimary: '#f472b6',
                sidebarPrimaryForeground: '#0d0208',
                sidebarAccent: '#2d0a1e',
                sidebarAccentForeground: '#fce7f3',
                sidebarBorder: '#4a0e2c',
                sidebarRing: '#f472b6',
            },
            radius: '0.75',
            fontFamily: 'Inter',
            heroVariant: 'centered',
            heroBackground: 'gradient',
        },
    },

    // ── 3. Emerald Forest ────────────────────────────────────────────────────
    {
        name: 'Emerald Forest',
        slug: 'emerald-forest',
        config: {
            light: {
                background: '#f0fdf4',
                foreground: '#052e16',
                card: '#ffffff',
                cardForeground: '#052e16',
                popover: '#ffffff',
                popoverForeground: '#052e16',
                primary: '#065f46',
                primaryForeground: '#ffffff',
                secondary: '#ecfdf5',
                secondaryForeground: '#065f46',
                muted: '#d1fae5',
                mutedForeground: '#166534',
                accent: '#10b981',
                accentForeground: '#ffffff',
                destructive: '#dc2626',
                border: '#a7f3d0',
                input: '#a7f3d0',
                ring: '#10b981',
                chart1: '#065f46',
                chart2: '#10b981',
                chart3: '#34d399',
                chart4: '#059669',
                chart5: '#047857',
                sidebar: '#ecfdf5',
                sidebarForeground: '#052e16',
                sidebarPrimary: '#065f46',
                sidebarPrimaryForeground: '#ffffff',
                sidebarAccent: '#d1fae5',
                sidebarAccentForeground: '#065f46',
                sidebarBorder: '#a7f3d0',
                sidebarRing: '#10b981',
            },
            dark: {
                background: '#020c06',
                foreground: '#d1fae5',
                card: '#052e16',
                cardForeground: '#d1fae5',
                popover: '#052e16',
                popoverForeground: '#d1fae5',
                primary: '#34d399',
                primaryForeground: '#020c06',
                secondary: '#064e3b',
                secondaryForeground: '#d1fae5',
                muted: '#064e3b',
                mutedForeground: '#6ee7b7',
                accent: '#10b981',
                accentForeground: '#020c06',
                destructive: '#7f1d1d',
                border: '#065f46',
                input: '#065f46',
                ring: '#34d399',
                chart1: '#34d399',
                chart2: '#6ee7b7',
                chart3: '#a7f3d0',
                chart4: '#10b981',
                chart5: '#d1fae5',
                sidebar: '#010802',
                sidebarForeground: '#6ee7b7',
                sidebarPrimary: '#34d399',
                sidebarPrimaryForeground: '#020c06',
                sidebarAccent: '#064e3b',
                sidebarAccentForeground: '#d1fae5',
                sidebarBorder: '#065f46',
                sidebarRing: '#34d399',
            },
            radius: '0.625',
            fontFamily: 'Inter',
            heroVariant: 'centered',
            heroBackground: 'mesh',
        },
    },
]

export async function runThemeSeed(db: NodePgDatabase<typeof schema>) {
    console.log('\nSeeding preset themes...')
    for (const preset of PRESET_THEMES) {
        const existing = await db.select().from(themes).where(eq(themes.slug, preset.slug)).limit(1)
        if (existing.length) {
            console.log(`  skip  theme: ${preset.name}`)
        } else {
            await db.insert(themes).values({ ...preset, isActive: false })
            console.log(`  seed  theme: ${preset.name}`)
        }
    }
}
